### ISSUE TITLE
Table Manager: Use Case für "Nicht in Datenbank speichern"

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#1]
Bräuchte dazu mal ein paar sinnvolle Beispiele, wann das notwendig ist, insb. bei so Sachen wie checkbox, date.

**Comment by dergel** [comment]
ich muss zugeben, dass ich diese fälle selten hatte. aber z.b. bei der checkbox will man nicht speichern, dass diese person die agbs oder datenschutzbestimmungen gelesen hat, sondern nur validieren, dass diese gelesen wurden.

Bei Date weiss ich keinen Fall.. Ich glaube ich würde die no_db attribute allgemein killen wollen, aber dennoch so einbauen, dass diese optional genutzt werden können. Nur leider es dann nciht mehr rückwärtskompatibel

**Comment by AWqxKAWERbXo** [comment]
Ok, damit kann ich wenigstens was anfangen. Ich frag noch etwas rum.

**Comment by AWqxKAWERbXo** [comment]
Sehe jetzt im Moment keine Möglichkeit, das irgendwo sinnvoll unterzubringen.

**Comment by skerbis** [comment]
Es gibt bestimmt eine deutsche Datenschutzbestimmung, die dir zwar erlaubt bestimmte Daten abzufragen aber nicht zu speichern.
