### ISSUE TITLE
Table Manager: Fehlermeldungen - wie Mehrsprachigkeit vorbereiten?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#10]
- Via SPROG / Frontend: PIPE, PHP-Notation
- Via lang-Datei / Backend: Table Manager

**Comment by AWqxKAWERbXo** [comment]
Im Backend, z.B. bei den Tabellen:
`translate:com_user`

Geht auch bei Feldern, allerdings müssen die Labels dann fürs Frontend (PHP/Pipe) angepasst werden.
- wo die Lang-Datei hinpacken? Reicht "projects"?

**Comment by AWqxKAWERbXo** [comment]
im Frontend funktionieren Platzhalter mit Sprog, gerade getestet beim SQL-Feld.

**Comment by AWqxKAWERbXo** [comment]
@skerbis / @tbaddade / @gharlan mal ne Frage: Wie macht ihr das, wenn ihr eine Tabelle in YForm habt, die im Backend übersetzt wird - und im Frontend mit YOrm über Sprog - da bräuchte man ja eigentlich 2 verschiedene Platzhalter für das Feldlabel gleichzeitig, einmal `translate:label` und einmal `[[label]]`. Wenn ich hierzu was in der Doku schreiben will, würde ich gleich dieses Problem mit lösen, wenn es dazu eine Lösung gibt.

Mir fällt nur ein, in dem Fall nicht YOrm zu verwenden, sondern das Formular zu kopieren und andere Platzhalter fürs Frontend auszuwählen.

**Comment by tbaddade** [comment]
> Wie macht ihr das

Ich hole das Formular nicht über Yorm, da die Ausgabe der Elemente meist anders dargestellt werden als im Backend.

Für alle relevanten Übersetzungen im Frontend nutze ich dann Sprog. So kann das Formular zentral abgelegt werden und via Block in den Sprachen hinzugefügt werden.
