### ISSUE TITLE
Choicefeld ersetzt einige Felder ab v3.0

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform_docs#100]
https://github.com/yakamara/redaxo_yform/issues/493

Folgende Felder werden entfernt da choice das alles abdeckt:

checkbox_sql = Deprecated; Verwende das Choice value
radio = Deprecated; Verwende das Choice value
radio_sql = Deprecated; Verwende das Choice value
select = Deprecated; Verwende das Choice value
select_sql = Deprecated; Verwende das Choice value

Doku wird kleiner müsste aber leider angepasst werden.

**Comment by kobebeef** [comment]
Bin gerade am ausprobieren: 
Wenn man in einem Select-Menü den ersten Option eine reine Zahl ist (im Bsp unten: 0) setzt, gibt's einen Fehler.

choice|anzahl|Feldname|Bitte wählen,1x,2x,3x,4x,5x|0|0|
--> funktioniert

choice|anzahl|Feldname|0,1x,2x,3x,4x,5x|0|0|
--> Fehler (InvalidArgumentException Expecting $text to be a String, "integer" given!)

**Comment by tbaddade** [comment]
@kobebeef Bitte alle weiteren Fehler[ in diesem Repo](https://github.com/yakamara/redaxo_yform) als Issue anlegen . Du bist hier im Doku Repo für das AddOn gelandet.

**Comment by kobebeef** [comment]
Sorry!

**Comment by AWqxKAWERbXo** [comment]
Wie setze ich ein gewähltes Feld auf required? Kann jemand ein Beispiel für die Callback-Funktionen geben, die je nach Option/Input-Value Attribute zurück gibt?

**Comment by dergel** [comment]
jemand zeit das choice feld zu dokumentieren ?

**Comment by tbaddade** [comment]
> jemand zeit das choice feld zu dokumentieren ?

Das hatte @dtpop bereits gemacht
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yform_modul_values.md#choice

**Comment by dergel** [comment]
ach wie cool.. dann nur noch die deprecated Felder entsprechend markieren..

**Comment by AWqxKAWERbXo** [comment]
ich habe die Definition auch mal in den Table Manager übernommen, aber hier müsste das ganze noch angeglichen werden, z.B. die Infos, wie die Werte in der Datenbank aufgebaut sind (json, kommasepariert, ...?)

**Comment by AWqxKAWERbXo** [comment]
@dtpop bitte darauf achten, an beiden Stellen (Table-Manager-Felder / Formulareingabe-Felder) auf deprecated hinzuweisen. Habe ich jetzt korrigiert.
