### ISSUE TITLE
Anpassungen: labelexist -> name_exists / existintable -> exists_in_table

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform_docs#102]
Die Namen haben sich nur geändert. Müsste angepasst werden

**Comment by AWqxKAWERbXo** [comment]
Siehe PR - kapiere nicht, was da jetzt rein muss, drin bleibt oder raus muss.

**Comment by tbaddade** [comment]
Die Validierungen heißen aktuell `in_names` und `in_table`.
