### ISSUE TITLE
float deprecated -> number

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform_docs#104]

**Comment by AWqxKAWERbXo** [comment]
Das hat sich noch mal geändert, oder? In 3.0/3.1 ist das nicht mehr deprecated?

**Comment by AWqxKAWERbXo** [comment]
Ist deprecated, wie ich gestern gemerkt habe. Also je so markieren in der Doku zum Formbuilder und Table Manager wie select, usw.
