### ISSUE TITLE
showvalue

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#105]
Laut YCom gibt es "showvalue" als Feldtyp.

**Comment by tbaddade** [comment]
Ist schon sehr lang dabei.
https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/showvalue.php

**Comment by AWqxKAWERbXo** [comment]
Kam bei der GitHub-Suche nicht als Treffer.

**Comment by AWqxKAWERbXo** [comment]
Moment, du redest nicht von der Doku, ich schon. :D

**Comment by tbaddade** [comment]
Wollte nur zeigen, wo es sich genau versteckt.

**Comment by AWqxKAWERbXo** [comment]
Was genau macht das Value denn noch gleich?

**Comment by AWqxKAWERbXo** [comment]
Ist bereits genannt.
