### ISSUE TITLE
E-Mail-Templates verwenden: value_pool auslesen

### ISSUE THREAD

**Issue by isospin** [yakamara/redaxo_yform_docs#107]
habe gerade vergeblich versucht das snippet **Variante 1: tpl2email in einem yForm-PHP-Modul simulieren** zu nutzen. 
erst nachdem ich `$this->params['value_pool']['email']` in `$yform->objparams['value_pool']['email']` geändert habe hat es funktioniert (yform 3.0-beta2)

https://github.com/yakamara/redaxo_yform_docs/edit/master/de_de/email_plugin_verwenden.md

**Comment by dergel** [comment]
Kannst du dazu einen PR machen ?

**Comment by AWqxKAWERbXo** [comment]
Der Link ist leider nicht mehr vorhanden.

Es kommt eben darauf an, in welchem Kontext man sich befindet - ob $this oder $yform dann richtig ist. Ist das wirklich ein Fehler in der Doku?

**Comment by AWqxKAWERbXo** [comment]
Wurde wohl schon korrigiert.
