### ISSUE TITLE
Table Manager: email - Wie läuft die Validierung ab?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#11]
wie findet die Prüfung statt? RFC-Standardkonform oder einfach nur nach @-Zeichen?

**Comment by dergel** [comment]
es gibt zwei .. validate|type|email und direkt validate|email|

bei beiden benutzen wir einen regex:
"#^[\w.+-]{2,}\@\w[\w.-]*.\w+$#u";

aber.. ich hätte nichts gegen eine konforme Lösung z.B.

https://github.com/iamcal/rfc822/blob/master/rfc822.php
https://gist.github.com/sepehr/3340008

Was meinst Du ? Unsere Variante ist halt etwas offener

**Comment by AWqxKAWERbXo** [comment]
Die höchstmögliche Konsistenz wäre doch sicher, die Validierung analog zur Client-Validierung (`<input type="email" />`) zu haben. Sonst hat man so Effekte, dass eine clientseitige Validierung fehlschlägt, die in Redaxo erlaubt ist und vice versa.

Aber ich weiß nicht, wie das bei Edge, Gecko, Webkit und Blink gehandhabt wird. Falls das geändert werden soll, sollte die Diskussion aber nicht hier in der Doku geführt werden.

**Comment by dergel** [comment]
das stimmt.. gehört dann eigentlich ins addon selber.

**Comment by AWqxKAWERbXo** [comment]
Ich schließe das Issue hier, weil es in der Doku erklärt wird. Bitte wieder aufmachen, wenn die Überprüfung nach RFC abläuft und die Doku bearbeitet werden soll.

**Comment by dergel** [comment]
https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address

ist nun nach browserstandard gesetzt
