### ISSUE TITLE
YORM doku ergänzen / klären

### ISSUE THREAD

**Issue by cukabeka** [yakamara/redaxo_yform_docs#111]
In der YORM Doku fehlen IMHO folgende Punkte:

1. Was genau ist der Vorteil, YORM zu verwenden? Werden die queries gecached im Unterschied zu rex_sql? In welchen Szenarien eignet sich YORM besonders? Wäre schön, dazu ein paar Worte am Anfang zu lesen.
2. Die eigene Klasse in der Doku https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yorm.md fehlt, dort ist nur eine leere Klasse erwähnt https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yorm.md#klasse-erstellen - wenn ich einsteige, ist verwirrend, dass in der definition der Klasse kein Code steht. Vielleicht ist nützlich, das zu ergänzen.

**Comment by AWqxKAWERbXo** [comment]
@cukabeka, kannst du die Doku dahingehend ergänzen? Ich könnte mir gut vorstellen, dass YOrm in Zukunft auch ein eigenes Kapitel bekommt und nicht nur eine Seite.

Da ich YOrm quasi nie verwende bisher, kann ich da nicht viel beitragen, helfe aber gerne, wenn du Fragen zum Schreiben oder bei der Korrektur hast.

**Comment by AWqxKAWERbXo** [comment]
@cukabeka möchtest du dich hier noch beteiligen?

**Comment by skerbis** [comment]
zu 2. In Tricks ist ein Beispiel: https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yorm.md#dataset-filter

**Comment by skerbis** [comment]
zu Punkt 1: https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yorm.md
