### ISSUE TITLE
upload: Speicherort und Hash-Wert im Dateinamen

### ISSUE THREAD

**Issue by claudihey** [yakamara/redaxo_yform_docs#113]
Wo werden die Dateien nach einem Upload physisch gespeichert?
Dateinamen werden um Hash-Wert ergänzt, wie kann man den Hash-Wert ermitteln und die Datei aufrufen?

**Comment by AWqxKAWERbXo** [comment]
@claudihey hast du darauf schon eine Antwort gefunden und kannst eine Korrektur in der Doku vornehmen?

Der Upload-Pfad ist übrigens sowas wie /redaxo/data/addons/yform/.../upload/[tabellenname]

**Comment by claudihey** [comment]
@alexplusde Leider nein, ich hatte es dann mit mediafile gelöst.

**Comment by AWqxKAWERbXo** [comment]
Siehe auch https://github.com/yakamara/redaxo_yform/issues/725

komme hier nicht weiter. @dergel ?
