### ISSUE TITLE
Links in Doku funktionieren nicht

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/redaxo_yform_docs#114]
Z.B. auf der Seite redaxo/index.php?page=yform/docs&yform_docs_file=demo_kontakt-spamschutz.md gibt es den Text WICHTIG: damit das funktioniert, muss real_field_names auf true stehen: Anleitung. Hinter Anleitung steht der Link /redaxo/yform_modul_objparams.md#echte-feldnamen. Es sollte aber folgender Link stehen: /redaxo/index.php?page=yform/docs&yform_docs_file=yform_modul_objparams.md

**Comment by AWqxKAWERbXo** [comment]
@TobiasKrais kannst du einen PR dazu machen?

**Comment by TobiasKrais** [comment]
Ich weiß nicht wie die Lösung aussehen muss. :-(

**Comment by AWqxKAWERbXo** [comment]
Hier bearbeiten: https://github.com/yakamara/redaxo_yform_docs/edit/master/de_de/demo_kontakt-spamschutz.md

**Comment by TobiasKrais** [comment]
Da funktionieren die Links auch nicht :-(

**Comment by elricco** [comment]
Also so wie es scheint greifen Links nicht, die noch einen zusätzlichen #anker am Dateinamen haben. Bei rest_plugin.md greift der Link auf die yorm.md, allerdings ist dort kein Anker angehängt.

**Comment by AWqxKAWERbXo** [comment]
Wenn man die Anker weglässt, dann passt es?

**Comment by AWqxKAWERbXo** [comment]
Auf Github scheinen die Sprunganker dahingehend zu funktionieren

**Comment by AWqxKAWERbXo** [comment]
Das habe ich verbockt, ich dachte, ich hätte alles erwischt. Ein PR wäre zwar nett gewesen, aber ich versuche das zeitnah im Repo von YForm zu fixen.

**Comment by TobiasKrais** [comment]
Danke @alxndr-w! Hab den Issue völlig vergessen...
