### ISSUE TITLE
Duplikate auflösen bzw. auf einer Seite erfassen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform_docs#116]
Wäre es nicht sinnvoller doppelte Seiten/Inhalte auf einer Seite zusammenzufassen. Das würde sicherlich auch das Pflegen erleichtern

| Table Manager (Verwaltung für das Backend) | vs | YForm-Formbuilder (Modul für das Frontend) |
| ---- | ---- | ---- | 
| Optionen einer Tabelle | <> | Objparams |
| Feldtypen | <> | Values in Bearbeitung goldfischpeter |
| Validierungen | <> | Validates |

**Comment by AWqxKAWERbXo** [comment]
Ja. Das ist historisch so entstanden, da es bspw. Feldtypen gibt, die man nur im Table Manager nutzen kann und umgekehrt Values, die es nicht für den Table Manager gibt.

Optionen einer Tabelle und Objparams sind allerdings komplett unterschiedliche Baustellen.

**Comment by AWqxKAWERbXo** [comment]
Ich sehe hier keine einfache Verbesserungsmöglichkeit. 

Das eine ist der Table Manager, das andere der Formbuilder und diese unterscheiden sich maßgeblich genug, um eine Trennung zu rechtfertigen. 

Wenn, dann müsste man Backend/Frontend sauber trennen und die Feldtypen-Definition in PHP-Schreibweise aus der Table Manager-Rubrik raus nehmen - nur in den YForm Formbuilder passen sie dann auch nicht.
