### ISSUE TITLE
Yform Tabelle im Backend editieren - Beispiel

### ISSUE THREAD

**Issue by steri-rex** [yakamara/redaxo_yform_docs#117]
Beispiel - man möchte die E-Mail Adresse in der Backendtabelle mit einem E-Mail Link klickbar machen.
![yform_tabelle_editieren](https://user-images.githubusercontent.com/3844106/51077893-d24da280-16ac-11e9-96c1-694eb57f765c.png)

In die boot.php vom Projekt Addon
```
function format_email($ep)
{
return '<a href="mailto:###email###">###email###</a>'; // email ist der Platzhalter für den VALUE von Spalte email
}

rex_extension::register('YFORM_DATA_LIST','my_rex_list_tweaks');

function my_rex_list_tweaks($ep)

{
 $list = $ep->getSubject();
//if ($ep->getParam('table')->getTableName() == 'rex_ycom_user') { // optional wenn nur bestimmte Tabelle verändert werden soll
 $list->setColumnFormat('email','custom','format_email'); // email ist die Spalte welche editiert werden soll
//}

}
```

**Comment by cukabeka** [comment]
Super Tipp, danke Dir!

Wundere mich nur über die Notation, dass am Anfang schon das RETURN steht und das Unabhängig von der FUNCTION ist. Was passiert denn, wenn ich mehrere Felder ändern will, zB Vorname mit einem Link ausstatten?

**Comment by AWqxKAWERbXo** [comment]
Ich glaube, da fehlt was vorne dran...

**Comment by AWqxKAWERbXo** [comment]
@steri-rex kannst du dein Beispiel noch mal überprüfen / korrigieren?

**Comment by steri-rex** [comment]
tatsächlich - da hat der editor was verschluckt - ist korrigiert

**Comment by AWqxKAWERbXo** [comment]
Sehr cooler Trick, eignet sich auch für das URL-Addon, wobei es da was eigenes geben wird. Nehme es bei nächster Gelegenheit mit auf.
