### ISSUE TITLE
Table Manager: be_manager_relation - Anzeigefeld falsch beschrieben

### ISSUE THREAD

**Issue by gharlan** [yakamara/redaxo_yform_docs#12]
> Feldname der Tabelle, dessen Werte als Select-Box oder im Popup angezeigt werden, bspw. `name`, `title AS name` oder `CONCAT('id', ' ', 'name') AS name`

Dort ist keine SQL-Syntax möglich, sondern es ist eine eigene. Man trennt die Felder einfach mit einem Komma, ohne `CONCAT`: 
`id, name`

Konstante Strings setzt man in Anführungszeichen: 
`id, " ", name`

Verwendet man als Anzeigefeld ein anderes Relationsfeld, wird dies aufgelöst, und dessen Anzeigefeld(-Kombi) genommen.

Beispiel: Wir haben eine Newstabelle mit einem Relationsfeld `author_id`. Dies hat als Anzeigefeld diese Kombi: `firstname, " ", lastname`
In einer anderen Tabelle gibt es nun ein Relationsfeld `news_id` wo man einen Newsartikel auswählen kann. In der Selectbox sollen die News im folgenden Format erscheinen: "Newstitel (Autor)".
Dazu notieren wir das Anzeigefeld so: 
`title, " (", author_id, ")"`

YForm erkennt, dass `author_id` ein Relationsfeld ist, und löst es gemäß dessen Anzeigefeld auf (Vorname und Nachname).
Heraus kommt dann sowas wie "Redaxo 5.2 ist raus (Gregor Harlan)".

Diese Auflösung erfolgt rekursiv, also beliebig tief.

**Comment by AWqxKAWERbXo** [comment]
Ich hätte schwören können, das schon so gemacht zu haben. Danke für den Hinweis, ich korrigiere es.

**Comment by gharlan** [comment]
https://github.com/yakamara/redaxo_xform/pull/229

Vielleicht hattest du den PR ja bei dir selbst integriert.

**Comment by AWqxKAWERbXo** [comment]
Hab ich nie gemacht, ich habe es bestimmt mit einem anderen Feld verwechselt.

**Comment by AWqxKAWERbXo** [comment]
Ist geändert.
