### ISSUE TITLE
Password ändern erweitern, sodass aktuelles Passwort mit abgefragt wird

### ISSUE THREAD

**Issue by rotzek** [yakamara/redaxo_yform_docs#122]
Hab ich grad aus slack entnommen, vielleicht noch generalisieren und php-Variante hinzufügen?

objparams|Error-occured|Es sind Fehler in Ihrer Eingabe vorhanden
objparams|form_showformafterupdate|1
objparams|hide_field_warning_messages|false
objparams|hide_top_warning_messages|true
objparams|submit_btn_show|false

html|||

html|||
html|||

### Passwort ändern * {{ form.required.fields }}
hidden|new_password_required|0

password|old_password|{{ old_password }}:*||no_db|#placeholder:_
validate|empty|old_password|{{ error_enter_old_password }}
validate|ycom_auth_password|old_password|{{ error_not_old_password }}

ycom_auth_password|password|{{ new_password }}:*|{"length":{"min":8},"letter":{"min":1},"lowercase":{"min":1},"uppercase":{"min":1}}|{{ error_password_policy }}|#placeholder:_
validate|empty|password|{{ error_enter_password }}
validate|compare|password|password_2|!=|{{ error_enter_password_same }}

password|password_2|{{ new_password_repeat }}:*||no_db|#placeholder:_

html|||

html|||
html|||

html|||

html|||{{ send }}
html|||

html|||
action|showtext|

{{ password_changed }}
|||1
action|ycom_auth_db

**Comment by AWqxKAWERbXo** [comment]
Falsche Doku. https://github.com/yakamara/redaxo_ycom/issues/241
