### ISSUE TITLE
alte patch-branches löschen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#134]
Warst du das @staabm, der bei FOR so einen Bot eingesetzt hat, der alte Branches entfernt? Könnte man den hier auch einhängen?

**Comment by staabm** [comment]
Ja war ich. Kann man überall wo das repo public ist


Hier hab ich aber keine rechte

**Comment by AWqxKAWERbXo** [comment]
@dergel einmal Rechte für @staabm büdde

**Comment by AWqxKAWERbXo** [comment]
ping @dergel

**Comment by AWqxKAWERbXo** [comment]
ping @dergel

**Comment by dergel** [comment]
@staabm Welcher Bot ist das ? .. Und was braucht das ? .. Actions gehen in diesem Konto leider nicht.

**Comment by staabm** [comment]
@dergel das geht mittlerweile nativ in github in den settings des repo - ohne robot 

![grafik](https://user-images.githubusercontent.com/120441/67201665-08237280-f407-11e9-94bc-e2d9e7965e0f.png)

dann werden die auotmatisch beim merge des PR gelöscht


![grafik](https://user-images.githubusercontent.com/120441/67201721-28533180-f407-11e9-9ce1-d8291e01b733.png)

**Comment by dergel** [comment]
ist nun aktiviert :) Danke @staabm

**Comment by AWqxKAWERbXo** [comment]
Die alten Branches existieren noch, kann ich alle außer master löschen?

**Comment by staabm** [comment]
alle die "merged" sind definitiv:

https://github.com/yakamara/redaxo_yform_docs/branches/stale

![grafik](https://user-images.githubusercontent.com/120441/67222132-02408800-f42d-11e9-9fe4-ded6cc6ce18f.png)

**Comment by AWqxKAWERbXo** [comment]
Die Ansicht kannte ich noch nicht, danke!
