### ISSUE TITLE
Feldtyp be_user fehlt in Doku

### ISSUE THREAD

**Issue by pschuchmann** [yakamara/redaxo_yform_docs#137]
Weil gerade eben im Slack darauf verwiesen wurde, das Feld be_user ist in der Doku noch nicht aufgeführt.

**Comment by AWqxKAWERbXo** [comment]
Was wird in der DB gespeichert, ID oder Login? 

Sollte man vielleicht auch eine Definition für den Table Manager hinterlegen? -> in YForm separates Issue.

**Comment by AWqxKAWERbXo** [comment]
Es gibt einige Felder, die keine Definition mitbringen, aber schon in YForm verbaut sind - recaptcha bspw., Das könnte man bei der Gelegenheit gleich beheben.

Kannst du mich da zeitlich unterstützen?

**Comment by pschuchmann** [comment]
Ich versuche es. Würde kommende Woche mal durch die verfügbaren Felder gehen und eine Auflistung machen, wo welches Feld noch nicht dokumentiert ist. Durchzusehen wären dann die Dokumentation TableManager  / FormBuilder. Und ich schaue nochmal nach den Sprungankern, da funktionieren auch einige nicht so 100%.

**Comment by AWqxKAWERbXo** [comment]
@pschuchmann kann ich noch mit einem PR hierzu rechnen?

**Comment by pschuchmann** [comment]
Dieses Jahr nicht mehr, sorry.
