### ISSUE TITLE
yFORM, Module: db_query

### ISSUE THREAD

**Issue by Goldfischpeter** [yakamara/redaxo_yform_docs#14]
Anwendungsbeispiel?

**Comment by dergel** [comment]
ich habe diese action in der yform angepasst, so dass sie nun etwas anders funktioniert - nicht wie in r4. d.h. nochmal ein update von yform ziehen wäre gut

ein anwendungsbeispiel:

```
text|name|Name
text|email|E-Mail
action|db_query|insert into rex_ycom_user set name = ?, email = ?|name,email
```

im prinzip hast du werte aus dem formular, und diese kannst du auf deinem eigenen query verwenden.
