### ISSUE TITLE
Choice Erklärung irreführend

### ISSUE THREAD

**Issue by godsdog** [yakamara/redaxo_yform_docs#142]
Moin, gerade beim nutzen des Choice Feldes bin ich über true/false = 1/0 gestolpert. In der Beschreibung steht: `[expanded type: boolean; default: false]|[multiple type: boolean; default: false]` Das steht nichts von 1 oder 0, sollte ergänzt werden.

**Comment by AWqxKAWERbXo** [comment]
Hallo @godsdog, danke für die Rückmeldung. Möchtest du vielleicht die Doku und die Feldbeschreibung dahingehend verbessern?

**Comment by godsdog** [comment]
Hab ein PR gestartet.
