### ISSUE TITLE
Doku für Hidden-Feld

### ISSUE THREAD

**Issue by schorschy** [yakamara/redaxo_yform_docs#143]
Da es in yForm kein Hidden-Feld mehr gibt sollte man irgendwo dokumentieren wie man eines mit einem Textfeld erzeugen kann.
`$yform->setValueField('text', array('feldname','','','','{"type":"hidden","value":"hier Wert eintragen"}'));`

**Comment by dergel** [comment]
wieso gibt es keins mehr ?

https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/hidden.php

**Comment by tbaddade** [comment]
Aus der Doku

> hidden
> definiert ein Feld, das nur serverseitig befüllt wird und nicht ausgegeben wird.

dieser Satz scheint nicht mehr korrekt zu sein. Das hidden Value wird im Quelltext ausgegeben.

**Comment by AWqxKAWERbXo** [comment]
Dann ist das ein Bug imho

**Comment by AWqxKAWERbXo** [comment]
@pgmrrobot ich bin mir ziemlich sicher, dass das funktioniert. Bitte nochmal ausprobieren und auf die Anzahl und Reihenfolge der Parameter achten. Frag mal @pixeldaniel nach der HRS-Website und der stillen Mail. Da bitte abgucken und melden, falls es dann immer noch nicht funktioniert.
