### ISSUE TITLE
Table Manager: id-Feld migrieren

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#15]
Wie funktioniert das?

**Comment by dergel** [comment]
das vorhandene primary autoincrement feld wird genommen und umbenannt. ist nur ein hilfsmittel, falls die vorhandene tabelle keine id mit autoincrement hat, was vorrausetzung für die yform-tabellen ist

**Comment by AWqxKAWERbXo** [comment]
d.h. das ist auch der Grund dafür, warum man `rex_article` nicht in YForm migrieren sollte, weil dann das `pid`-Feld umbenannt wird, oder?

**Comment by dergel** [comment]
genau
