### ISSUE TITLE
YForm doku wie Tricks

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform_docs#161]
Ich schlage vor die YForm-Doku nach GitHub auf Basis der Tricks-Seite zu realisieren. 
Dies ermöglicht eine einfachere Bearbeitung und bietet zudem eine Volltextsuche.

**Comment by AWqxKAWERbXo** [comment]
Bin ich vollkommen damit einverstanden, allerdings müsste dann das Docs-Plugin überarbeitet werden, das die Darstellung im Backend managed. Hier bietet R5.9 entsprechende Funktionen, die auch md-Dateien parsen und im Backend darstellen können.

Da wünsche ich mir @dergel im Boot (wegen urspr. Docs-Lösung), ebenso wie @aeberhard wegen https://github.com/FriendsOfREDAXO/demo_addon/tree/master/plugins/documentation und Dirk, weil er doch die Tricksseite gemacht hat.

**Comment by tbaddade** [comment]
Ich könnte es mir auch direkt auf der Website vorstellen.

**Comment by AWqxKAWERbXo** [comment]
Hannover: Gut wäre eigentlich, wenn es eine Lösung gibt, die auch andere Addons so adaptieren können.

**Comment by AWqxKAWERbXo** [comment]
Siehe https://github.com/yakamara/redaxo_yform/pull/837
