### ISSUE TITLE
Repo schreibgeschützt stellen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#162]
Die issues hier sollten noch erreichbar bleiben, aber keine neuen PRs angenommen werden, da nun alles im YForm-Repo stattfindet.

**Comment by gharlan** [comment]
Wenn man das macht, kann man danach gar nix mehr in den Issue machen, also sie auch nicht mehr schließen etc.
Ist das so gewünscht?

**Comment by AWqxKAWERbXo** [comment]
@gharlan ich hatte gehofft am Hannover-Wochenende eine Vielzahl der Themen hier zu bearbeiten und die restlichen zu übertragen.

Der Einwand ist berechtigt.

Aber PRs von außen kann man sperren meines Wissens, oder?

**Comment by gharlan** [comment]
Nein, PRs sind einige der wenigen Dinge, die man gründsätzlich nicht abschalten kann (auch nicht beschränken).
Den Reiter Issues kann man ganz entfernen, auch Projekte und Wiki. Aber PRs nicht.

**Comment by AWqxKAWERbXo** [comment]
Ok. Dann nutze ich den Betreff dieses gepinnten Issues, um nochmal deutlich zu machen, dass die Doku jetzt wo anders liegt.

Und im master-Branch sollten wir nur die README.md lassen - einverstanden?

**Comment by AWqxKAWERbXo** [comment]
Diese Zeile hier bitte auch noch ändern und das YForm-Repo verlinken.
![image](https://user-images.githubusercontent.com/3855487/77316933-924f6a00-6d0a-11ea-8e75-906ee0fca1f8.png)

**Comment by AWqxKAWERbXo** [comment]
Gerade auch erst entdeckt, dass sich Issues transferieren lassen. Das wäre noch eine Möglichkeit. Dann kann man hier dicht machen.

![image](https://user-images.githubusercontent.com/3855487/77317049-c460cc00-6d0a-11ea-93f9-35c48ea27479.png)

**Comment by AWqxKAWERbXo** [comment]
@gharlan ich kann das nicht transferieren, mangels Berechtigung. Wäre das von Yakamaras Seite erwünscht, die Issues in YForm rüberzunehmen?

**Comment by gharlan** [comment]
Ich kann es auch nicht, da scheinen mir Rechte für zu fehlen.
Aber so oder so wäre es sehr viel Arbeit, daher würde ich eher nicht von ausgehen, dass das jemand macht.
