### ISSUE TITLE
Table Manager: compare: Nützliche Beispiele?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#17]
Hier hätte ich gerne ein paar typische Anwendungsszenarien genannt. Ideen?

**Comment by Goldfischpeter** [comment]
hier könnte man zwei Feld-Eingaben vergleichen, zb PLZ oder E-Mail-Adressen

text|plz1|PLZ|
text|plz2|PLZ wiederholen|
validate|compare|plz1|plz2|!=|Die beiden Felder haben unterschiedliche Eingaben!

**Comment by phoebusryan** [comment]
Häuft genutzt bei Passwörtern.. ;)

**Comment by AWqxKAWERbXo** [comment]
@Goldfischpeter @phoebusryan bei Passwörtern habe ich es auch schon drinstehen, aber wann benötigt man die anderen Operatoren wie != etc.?

**Comment by Goldfischpeter** [comment]
Da würde mich jetzt auch ein Konfigurator oder ein Online-Tarif-Rechner einfallen, wo Eingaben vor Berechnung miteinander verglichen werden.

**Comment by AWqxKAWERbXo** [comment]
Das ist eine gute Idee.
