### ISSUE TITLE
Table Manager: unique: Welche Felder werden durchsucht?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#18]
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/table_manager_validierungen.md#unique

Verstehe ich das Szenario richtig: 
1. Jemand gibt eine E-Mail-Adresse, bspw. max@mustermann.de, im Formular in das Feld "email" ein.
2. unique durchsucht _alle_ Felder der aktuellen Tabelle, bzw. der in "Tabelle [opt]" angegeben Tabelle nach diesem Wert und gibt false zurück, wenn er gefunden wird.

D.h. umgekehrt, dass ich nicht in nur einem Feld einer Datenbank-Tabelle suchen kann, sondern immer in allen gesucht wird?

**Comment by Goldfischpeter** [comment]
Die methode durchsucht die angegebenen Felder, nicht alle Felder.

**Comment by Goldfischpeter** [comment]
Im Modul werden diese Felder komma-getrennt definiert
validate|unique|dbfeldname[,dbfeldname2]|Dieser Name existiert schon|[table]

**Comment by AWqxKAWERbXo** [comment]
edit: mir geht es um [table]. Heißt also, dass im Table Manager keine Möglichkeit besteht, einen bestimmten Feldnamen einer fremden Tabelle anzugeben, weil man die Felder via select auswählen muss? @gharlan 

![image](https://cloud.githubusercontent.com/assets/3855487/16706517/487dd810-45b0-11e6-9035-3bd4428cd80b.png)

**Comment by dergel** [comment]
stimmt.. das ist unlogisch. Hier eine optinale Tabelle auszuwählen ist quatsch, da die felder dasnicht hergeben.. kannst du das als issue in die yform selbst setzen ?
