### ISSUE TITLE
Table Manager: be_table-Feld - welches Format?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#2]
Wenn eine be_table befüllt wird, was enthält dann das Feld im Backend? csv mit Komma+Semikolon? Komma+Newline? JSON?

**Comment by AWqxKAWERbXo** [comment]
CSV. Leider mit Bugs.

https://github.com/yakamara/redaxo_yform/issues/109

**Comment by AWqxKAWERbXo** [comment]
JSON seit 2.0

**Comment by AWqxKAWERbXo** [comment]
Howto übernehmen
http://www.redaxo.org/de/forum/post120365.html

**Comment by skerbis** [comment]
@alexplusde Link nicht verfügbar

**Comment by AWqxKAWERbXo** [comment]
Edit: Ich hatte verlinkt auf
https://stackoverflow.com/questions/26213049/how-can-i-parse-json-into-a-html-table-using-php
bzw.
https://redaxo.org/forum/viewtopic.php?t=120365&p=120365#p120365

Da gibt's ein Beispiel, das wollte ich mit aufnehmen.

**Comment by skerbis** [comment]
War wohl das hier? https://redaxo.org/forum/addons-packages-r5-f43/ausgabe-yform-be_table-t21468.html

**Comment by gharlan** [comment]
Habe eine Weiterleitung für die alten Links in der Form `de/forum/postXXX.html` eingerichtet.
