### ISSUE TITLE
Table Manager: Unterschied hashvalue / index

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#21]
Machen die beide nicht mehr oder weniger das gleiche? Könnte man die nicht zusammenfassen? @dergel

**Comment by dergel** [comment]
das gleiche nicht, aber mit dem index kann man den hashvalue auch simulieren.. wenn auch nicht ganz gleich

index: erstellt, wenn man keine function reinlegt, einen index aus den veschiendenen feldern. z.B. für einen volltextsuche. Man könnte in einem datensatz z.b. vorname, nachname, strasse, ort reinnehmen und hätte einvoll textsuchfeld für die adressen. man kann das ergebnis durch eine function laufen lassen und damit auch einen hashvalue erzeugen. Aber es würde, sofern die werte identisch sind, immer der gleich hashwert rauskommen

hashvalue: ausschliesslich da um einen key zu erstellen. Nichts mit Volltextsuche etc.

**Comment by AWqxKAWERbXo** [comment]
ok, hashvalue erzeugt immer, auch bei identischen Werten, unterschiedliche Hashs.
