### ISSUE TITLE
Table Manager: datestamp: Formate erklären

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#22]
Wert in der Datenbank: `TueAMCESTEthCESTAMJul+02:00`

@dergel

**Comment by dergel** [comment]
das müsste doch davon abhängen was du als Format eingetragen hast, oder ?

**Comment by AWqxKAWERbXo** [comment]
Ah... in der Doku waren die falschen Optionen genannt und in meiner Testtabelle habe ich bei Format im Übereifer eine Bezeichnung eingegeben...

... womit wir eigentlich bei https://github.com/yakamara/redaxo_yform/issues/72 wären. Das Feld `datestamp` kann nicht beschriftet werden und Format steht in `label`, wo es eigentlich nicht hingehört.

(Memo für mich: Beispiel zu den Formaten in die Doku)
