### ISSUE TITLE
Table Manager: HowTo: Mit 2. Datenbank verbinden.

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#28]
Früher war es ja möglich, in der master.inc.php in R4 eine 2. Datenbankverbindung zu hinterlegen. Das geht ja auch in R5.

Und ich lese zwischen den Zeilen öfters, dass der Table Manager auch auf die 2. Datenbankverbindung zugreifen kann. Wie funktioniert das? Verstehe ich da was falsch?

**Comment by phoebusryan** [comment]
Du kannst in der config.yml eine zweite Datenbank angeben und so dann verwenden. Das ist gleich wie in R4.

**Comment by AWqxKAWERbXo** [comment]
Auch in R4 habe ich das nie gemacht. 

Sind alle Tabellen der 2. Datenbank dann direkt im Table Manager verfügbar? Was ist, wenn ich auf eine Datenbank-Tabelle in Datenbank 2 zugreifen will, die auch in Datenbank 1 existiert?

**Comment by AWqxKAWERbXo** [comment]
Die 2. Datenbank ist bisher nicht Teil des Table Managers.
