### ISSUE TITLE
Aktualisierung von Formulardaten

### ISSUE THREAD

**Issue by nilskoppelmann** [yakamara/redaxo_yform_docs#30]
Laut [doku](https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yform_modul_actions.md#db) soll das ja mit folgendem Code in Pipe Notation gehen:

```
action|db|tblname|[where(id=2)/main_where]

im YForm-Formbuilder
text|vorname|Vorname
text|name|Name
text|plz|PLZ
text|ort|Ort

action|db|rex_warenkorb
action|html|Daten gespeichert
```

Und die PHP Version dieses Beispiels scheint mir auch nicht komplett zu sein:

``` php
$yform = rex_yform::factory();
// aus dem Beispiel
$yform->setValueField('text', array("vorname","Vorname"));
$yform->setValueField('text', array("name","Name"));
$yform->setValueField('text', array("plz","PLZ"));
$yform->setValueField('text', array("ort","Ort"));

$yform->setActionField('db', array("rex_warenkorb"));
$yform->setActionField('html', array("Daten gespeichert"));

echo $yform->getForm();
```

Was ich eben erreichen möchte ist Formulardaten zu aktualisieren und den Code dafür in Pipe Notation aus einer Datenbank holen und `action|db|tblname|[where(id=2)/main_where]` hier die `id` durch einen Wert ersetzen. Letztlich den Formularcode ähnlich wie im Formbuilder mit `yform->setFormData($formData)` ausgeben.

**Comment by nilskoppelmann** [comment]
Also das Ändern des Datensatzes funktioniert bei mir mit der Pipe Notation schon (inzwischen auch mit `$yform->setFormData($form_data)`), nur das vorherige Einsetzten der bisherigen Daten nicht …

Sprich wenn `value1` in der Datenbank bisher `xyz` war möchte ich, dass es auch direkt im Formular auftaucht und ich es dann ändern kann.

**Comment by nilskoppelmann** [comment]
Habe inzwischen herausgefunden wie es funktioniert … Pull Request vorhanden.

**Comment by Goldfischpeter** [comment]
Der Code in der Doku funktioniert. 
Das Ändern eines Datensatzes ist ein anderes Beispiel. Beispiele, Best Practices wird es noch geben.

**Comment by AWqxKAWERbXo** [comment]
Für mich ist es überhaupt nicht ersichtlich, was bspw. mit "main_where"gemeint ist, und warum das in der PHP-Notation komplett fehlt.

**Comment by nilskoppelmann** [comment]
main_where wird via `objparams|main_where|where_clause` wobei `where_clause` folgendermaßen aussehen könnte: `id=5`.

In PHP (Beispiel aus meinem Code):

``` php

$url = rex_getUrl(REX_ARTICLE_ID,REX_CLANG_ID) . '?id=' . $slot_id . '&func=edit';
            $yform = rex_yform::factory();
            $yform->setObjectparams("getdata",TRUE);
            $yform->setObjectparams('form_action', $url);
            $yform->setObjectparams('main_table', $table); // $table: table_name
            $yform->setObjectparams('main_where', 'id='. $slot_id);
            $yform->setFormData($form_data); // $form_data: pipenotation aus der Datenbank
            $yform->setActionField('db', array("$table", "main_where"));
            echo $yform->getForm();
```

**Comment by AWqxKAWERbXo** [comment]
Hab deinen PR gerade dazu entdeckt
https://github.com/yakamara/redaxo_yform_docs/pull/31

Am besten wäre es, den PR so anpassen, dass das Beispiel ergänzt wird und nicht ersetzt, oder?

**Comment by AWqxKAWERbXo** [comment]
@nilsology @Goldfischpeter wenn ihr das besser wisst / kennt, könnt ihr bitte dazu nochmal Demo-Code posten?

**Comment by skerbis** [comment]
Fertiges Formular inkl. Daten zur Bearbeitung holen
(_Darauf achten, dass keine be_felder - verwendet werden_)

```
<?php 
// Datensatz aus Tabelle mit ID 2
$dataset = rex_yform_manager_dataset::get(2,Tabelle);
// Formular auslesen
$yform = $dataset->getForm();
// Parameter festlegen
$yform->setObjectparams('form_method','get');
// Ziel des Formulars, sonst erhält man nur Index.php ...
$yform->setObjectparams('form_action',rex_getUrl(13));
// Sollen die Daten des Datensatzes ausgelesen werden? (true = ja , false = nein) 
$yform->setObjectparams("getdata",true);
echo $dataset->executeForm($yform);
} ?>
```

**Comment by AWqxKAWERbXo** [comment]
An dem Beispiel nicht ideal finde ich die Verwendung des Datasets ... das könnten wir für die Doku zwar grundsätzlich mit aufnehmen, aber der Weg ohne sollte weiterhin ersichtlich sein. Es gibt Szenarien, da hat man die Tabelle nicht im Table Manager.

**Comment by AWqxKAWERbXo** [comment]
Das Dataset ist jetzt bei YOrm genannt https://github.com/alxndr-w/redaxo_yform/blob/patch-6/docs/yorm.md - Beispielcodes können auch dort noch verbessert und verallgemeinert werden als PR bitte.
