### ISSUE TITLE
Honeypot / Spamschutz

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#33]
Formulare, die im Frontend ausgegeben werden, benötigen in aller Regel einen Spamschutz. Hier könnte man in der Doku Beispiele zur Umsetzung machen.

Lösungsansatz honeypot http://www.redaxo.org/de/forum/php-html-css-mysql-f9/submit-button-disabled-spamschutz-t21308.html (Fragestellung: Geht das Prinzip auch ohne extra Klasse?)

Lösungsansatz zeitspanne: ____

Weitere Lösungsansätze?

**Comment by dergel** [comment]
In der DOku aufnehmen super !! .. und eventuell ergeben sich hier ein paar sinnvolle ValueKlassen welche wir aufnehmen sollten .. CSRF gehört auch mit zu diesem Thema

**Comment by AWqxKAWERbXo** [comment]
Wie bekomme ich denn mit, wann das Formular an den Browser übermittelt wurde? datestamp wird ja erst gesetzt, wenn der Datenbankeintrag abgelegt wurde. Dann könnte man den Ansatz mit der Zeitspanne ja ganz einfach über eine Custom Function lösen.

**Comment by dergel** [comment]
es wird ein objparameter "send" mitgeliefert.. Ist in fast jeder der value klassen zu sehen.

**Comment by AWqxKAWERbXo** [comment]
Ich habe mich missverständlich ausgedrückt. Wissen wollte ich, ob man den Zeitpunkt, wann das Formular übermittelt wurde, herausfinden kann. Wahrscheinlich muss ich mir dazu mal anschauen, wie "hidden" genau funktioniert und das Feld initial im Formular mit einem Zeitstempel befüllen.

**Comment by AWqxKAWERbXo** [comment]
Ich hab da mal was vorbereitet.
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/demo_kontakt-spamschutz.md

Bitte gegenlesen.

**Comment by dergel** [comment]
klingt gut..  und in die yform sollte man noch weitere formen aufnehmen.. key in session speichern etc.

**Comment by skerbis** [comment]
Für den letzen Punkt: autocomplete="off" hilft hier

**Comment by AWqxKAWERbXo** [comment]
@skerbis danke, dann als Attribut `{"autocomplete":"off"}` - PR willkommen :)
