### ISSUE TITLE
Import erklären

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform_docs#36]
Beim Import wird jeder Datensatz "simuliert" eingegeben. D.h. es durchläuft die Validierungen und Indexierungen und Funktionen, als ob man es manuell eingegeben hätte. Und demnach kann ein Import auch mal Fehlschlagen

**Comment by AWqxKAWERbXo** [comment]
Schlägt der Import dann komplett fehl oder können Daten trotzdem partiell importiert werden? War das Verhalten mit dem simulierten Eingeben immer schon so oder erst jetzt?

**Comment by dergel** [comment]
nur den enstsprechende Datensatz wird nicht importiert - der Rest geht .

> War das Verhalten mit dem simulierten Eingeben immer schon so oder erst jetzt?

das ist neu, also war nicht in Version 1.0

**Comment by AWqxKAWERbXo** [comment]
Bereit für den PR.
