### ISSUE TITLE
Umbau date / time / datetime

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform_docs#37]
Formatierungen, Widgets (select oder inputfeld darstellung) mit attributen (z.b. Datepicker oder inputmask) verknüpfbar

**Comment by AWqxKAWERbXo** [comment]
Wird bereits angedeutet in https://github.com/yakamara/redaxo_yform/blob/97513335d16c389b8e139aae4c931c67aee44d6e/docs/formbuilder.md#datetime
