### ISSUE TITLE
MultiEdit-Mode

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform_docs#38]
Mehrfachbearbeiten von Suchergebnissen nun möglich.

Man kann einzele Felder bearbeiten. Jeder Datensatz wird dann nur um diese Änderung ergänzt und durchläuft bei der Veränderungen den normalen Eingabeprozess. D.h. auch Validierungen werden geprüft und eventuelle Funktionen werden durchgeführt

**Comment by AWqxKAWERbXo** [comment]
Cool.

**Comment by dergel** [comment]
- jede Veränderung an jedem Datensatz wird natürlch in der Historie aufgenommen.

**Comment by AWqxKAWERbXo** [comment]
Hab es gerade mal getestet - es geht wirklich sehr unter. Scheint aber gut zu funktionieren :) Ich hoffe, es beizeiten mit aufnehmen zu können in die Table Manager-Infos.
