### ISSUE TITLE
Mini ORM ergänzt

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform_docs#40]
hier müsste Gregor schreiben wie man es ungefähr nutzt. Es gibt aber auch in den Issues bei yform ein paar Beispiele. Wenn man die Daten über dieses ORM verwendet, ziehen auch automatische die Historyfunktionen.

**Comment by AWqxKAWERbXo** [comment]
https://github.com/yakamara/redaxo_yform/issues/205

**Comment by skerbis** [comment]
Hinweis zu History ergänzt, Yorm Anleitung erweitert mit Trick 😘
