### ISSUE TITLE
Diverse Feldergänzungen. Notices, Attributes ...

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_yform_docs#41]
wurden an verschiedensten Feldern ergänzt .. Ein Review der Felder kann nicht schaden.. Sorry, war echt einiges..

**Comment by AWqxKAWERbXo** [comment]
I know... gut, dass die Commits in der Regel gut beschrieben sind. @pixelfirma wird sich evtl. darum kümmern.

**Comment by AWqxKAWERbXo** [comment]
Hier hat sich über die 4-5 Jahre so viel angestaut, dass man generell bei allem drüber schauen sollte.
