### ISSUE TITLE
Table Manager / Tools Plugin: Tags

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#43]
Siehe https://github.com/yakamara/redaxo_yform/issues/173

**Comment by AWqxKAWERbXo** [comment]
Es gibt dazu mittlerweile Addons und Lösungen mit Select2 bspw. - Hier fehlt es an Erläuterungen oder zumindest einem Verweis.

**Comment by fietstouring** [comment]
Gibts irgendwo einen Hinweis wie man sowas mit Tags wie in dem Screenshot von yform hier auf github umsetzt?

**Comment by AWqxKAWERbXo** [comment]
https://github.com/yakamara/redaxo_yform/issues/173#issuecomment-252226231
