### ISSUE TITLE
Table Manager: email vs text+email(validate)

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#5]
Wo ist der Unterschied zwischen einem Feldtyp E-Mail und einem Textfeld mit Validierungsoption E-Mail? (Wäre das nicht ein Feld, das man aus yform kicken könnte @dergel?)

**Comment by dergel** [comment]
sind identisch .. ja.. könnte man kicken - wenn es nicht schon so häufig verwendet werden würde.

**Comment by AWqxKAWERbXo** [comment]
Idee: Als deprecated markieren, damit man es in yform 1.3 kicken kann.

**Comment by AWqxKAWERbXo** [comment]
Ich mach hier zu, weil die Frage für die Doku beantwortet ist.
