### ISSUE TITLE
objparams: mehrere Templates hinterlegen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#53]
```
objparam|form_ytemplate|dein_template,bootstrap
```

Todo
* Howto: Eigene Templates schreiben, ablegen (Struktur), Anwendungsszenarien)

@tbaddade

**Comment by tbaddade** [comment]
in die boot.php des Project AddOns

`rex_yform::addTemplatePath($this->getPath('ytemplates'));`

**Comment by AWqxKAWERbXo** [comment]
Wird in der aktuellen Doku bereits erläutert.
