### ISSUE TITLE
docs.css wurde nicht gefunden

### ISSUE THREAD

**Issue by staabm** [yakamara/redaxo_yform_docs#55]
in rex5.2 habe ich yform 2.0 mit docs 2.0 installiert.

in den firefox devtools sehe ich dass eine http://localhost/redaxo_5.2.0/assets/addons/yform/plugins/docs/docs.css nicht geladen werde kann... 404...

im physikalischen ordner auf der platte existiert auch kein unterordner /docs/doc.css

php5.6.15
win10

**Comment by AWqxKAWERbXo** [comment]
Das Doku-Plugin separat gibt's ja nicht mehr, daher schließe ich hier.
