### ISSUE TITLE
Table Manager: submits: use case für mehrere submits

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#6]
Wann ergibt das Sinn? Konkretes Beispiel wäre super.

**Comment by dergel** [comment]
ich kann den submits values hinterlegen, die dann auch in der datenbank gespeichert werden können, oder z.b. im email template über php ausgewertet werden .. ich habe keinen konkreten fall parat

**Comment by AWqxKAWERbXo** [comment]
Ok, verstehe. Vielleicht findet sich auch hier was konkretes, z.B. "Bestellen" vs. "Angebot anfragen" oder so.
