### ISSUE TITLE
Table Manager: Best Practice für Tabellen, Felder & Namespaces

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#61]
Eher Doku oder eher FOR-Tricks?

**Grobes Inhaltsverzeichnis:**

1.	**Tabellen-Präfix**
a.	rex_yf_ Für Datentabellen
b.	rex_yfr_tabelle1_tabelle2 für Relationstabellen, als Name „Tabelle 1 ↔ Tabelle 2“
c.	rex_yfv_ für Views: Um Views zu erstellen muss der Hoster dem Nutzer das passende DB-User-Recht freischalten
2.	**Tabellen- und Feldnamen möglichst in Englisch**
a.	team für Mitarbeiter / Team / Personen
b.	messages für Kontaktformulare
c.	products für Produkte / Artikel etc.
d.	events für kalendarische Daten (Termine, Veranstaltungen, etc.)
3.	**Tabellen erstellen**
a.	Aktiv JA
b.	Sortierung zunächst id
c.	Suche aktiv JA
d.	Export erlauben JA
e.	Import erlauben JA
f.	Massenlöschung erlauben JA
g.	Historie anlegen JA
4.	**Felder erstellen**
a.	firstname | text | für Vornamen
a.     lastname | text | für Nachnamen
b.	name | text | für Namen, Überschrfiften, Titel, Artikelnamen, etc.
b.     name_$clang | text | für mehrsprachige Namen, Titel, Überschriften
c.	status | checkbox | für online/nicht online
d.	email | text | für E-Mails
e.	image | be_media | für ein einzelnes Bild
f.	images | be_media | für Bilder
g.	description | textarea | für HTML-Text (Redactor)
h.	createdate | datestamp | Zeitstempel
i.	updatedate | datestamp | Zeitstempel
j.	_id oder _ids als Suffix für Fremdschlüssel / Relationsschlüssel und SQL-Select
k.	token | hashvalue | für einmalige Aktivierungscodes (bspw. E-Mail-Freischaltung)
l.	Nach dem Felder-Erstellen die Sortierreihenfolge logisch einstellen (Datum DESC bei Terminen, Produkte, etc.) und ggf. Anzahl der Datensätze pro Seite anpassen
5.	**Validierungen**
a.	name | empty
b.	email | empty + email
c.	unique, wenn ein Feld oder eine Feld-Kombination als URL-Slug dient 
d.	Weitere Validierungen je nach Sinn und Zweck
i.	Pflichtfelder -> empty
ii.	URL-Felder -> unique
6.	**Objekt-Parameter**
a.	(ergänze ich noch)
7.	**Ausgabe (YOrm / MySQL)**
a.	(ergänze ich noch)

**Comment by dergel** [comment]
Doku wäre cool - aber wohl auch sehr aufwändig .. Vielleicht eher Tricks mit Beispielen ?

**Comment by IngoWinter** [comment]
- Tabellenpräfixe sind über
- Tabellennamen Singular, englisch, Unterstrich

**Comment by AWqxKAWERbXo** [comment]
Memo via @IngoWinter: 
first_name statt prename

**Comment by AWqxKAWERbXo** [comment]
> Doku wäre cool - aber wohl auch sehr aufwändig .. Vielleicht eher Tricks mit Beispielen ?

Wir müssen das eh bei uns im Haus mal festlegen, weil da keiner den Schwerpunkt Datenbanken hatte.

**Comment by AWqxKAWERbXo** [comment]
@IngoWinter 

> Tabellennamen Singular, English, Unterstrich

Das hat mich immer verwundert. Eine Tabelle beinhaltet doch 0-n Datensätze, warum man da nicht Plural nimmt?

**Comment by IngoWinter** [comment]
Die rex_article speichert lauter einzelne article Datensätze - man sagt ja auch Kartoffelsack und nicht Kartoffelnsack. Wenn mans so sieht, ist Singular richtig. Der wesentlich interessantere (weil praxisrelevante) Punkt ist aber: Singular ist einfacher, kürzer, eindeutiger (rex_octopus). Spätestens wenn du anfängst neue Tabellennamen aus bestehenden zu bilden, wirst du mit Plural wuschig.

**Comment by gharlan** [comment]
* Ich bevorzuge auch Tabellennamen im Singular. Wirklich begründen kann ich es nicht, ist aber glaube ich üblicher. Ich bin es jedenfalls so gewohnt.
* Ich würde keine unterschiedlichen Präfixe nehmen für normale und Relationstabellen, sondern einheitlich. Ist aber auch eher eine Geschmacksfrage. Es kommt aber vor, dass ich unterschiedliche Präfixe für einzelne Teilbereiche nehme. Im Zweifel nehme ich meist `rex_data_`.
* Immer `name` finde ich nicht unbedingt passend, wenn es eigentlich ein `title` ist.

Und wie schon in Slack geschrieben, bin ich mir aber auch unsicher, ob man da wirklich allgemein etwas empfehlen sollte oder ob sich da nicht jedes Team eigene Richtlinien geben sollte.

**Comment by IngoWinter** [comment]
Zumindest so detailliert wie oben gehörts ins firmeninterne Repo und nicht nach FOR. Eine allgemein gehaltene Empfehlung ist nicht verkehrt, allerdings kann man stattdessen auch eine Google Suche nach "mysql naming conventions" verlinken^^

**Comment by AWqxKAWERbXo** [comment]
Naja, "Richtlinien" wäre auch zu hoch gegriffen. Es wäre halt ein Vorschlag und als Zielgruppe für diejenigen, die zwar vlt. Einheitliches wollen, aber sich keine großen Gedanken machen wollen, warum. 

name/title -> umgeht bei be_relation die Fälle, in denen dann extra Anpassungen vorgenommen werden müssen. (title as name, etc.)
