### ISSUE TITLE
mehrere Attribute

### ISSUE THREAD

**Issue by IngoWinter** [yakamara/redaxo_yform_docs#62]
`|#placeholder:xxx|#required:required` <- so können mehrere attribute definiert werden. sollte sinnvoll irgendwo untergebracht werden, sonst weiss es keiner

**Comment by AWqxKAWERbXo** [comment]
Danke! Ihr habt im Slack-Channel einige Beispiele genannt...

Wenn ich mich richtig erinnere, ist es quasi egal, wo die mit # markierten Attribute auftauchen?

Was ist der Vorteil zur JSON-Schreibweise, die es seit YForm 2.0(?) für alle Felder gibt, um zusätzliche Attribute zu übergeben?

**Comment by AWqxKAWERbXo** [comment]
https://github.com/FriendsOfREDAXO/tricks/issues/18

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/tricks/issues/19

**Comment by AWqxKAWERbXo** [comment]
In einem anderen Issue hatte ich mich mit @dergel darauf verständigt, dass wir die `#`-Notation nicht mehr kommunizieren. Die Beispiele mit select sind eh hinfällig durch choice, bei allem anderen ist es schon dokumentiert, daher schließe ich das mal, außer, es gibt ein gutes Gegenargument.
