### ISSUE TITLE
default-Wert angeben

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#66]
Anregung von @phoebusryan - Die Parameter des YForm-Objekts werden nicht erläutert, bspw. default-Wert.

**Comment by skerbis** [comment]
Was ist gemeint?

**Comment by AWqxKAWERbXo** [comment]
Ich glaube, es ging um objparams und deren default-Werte, wenn diese nicht manuell überschrieben werden.

z.B. template: `bootstrap`

**Comment by AWqxKAWERbXo** [comment]
Wurde bei den Objparams gemacht. Toll - mir ist nicht klar, wer's gemacht hat, aber schon mal Danke.
