### ISSUE TITLE
Struktur der Doku

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform_docs#67]
Ich finde leider in der Doku nie, nach was ich aktuell suche. Soeben suchte ich grad das main_where als PHP-Notation. Auch die ganzen obj_params lassen sich schwer finden, da diese in der TOC nicht tatsächlich gelistet sind.

Daher die Anregung, dass man die aktuelle Struktur der Doku überdenken sollte.

**Comment by polarpixel** [comment]
Ist schwer, jeder hat ja seine eigene Logik und Ideen, wie es übersichtlich sein könnte. Deswegen ist mir "Struktur überdenken" jetzt zu allgemein, um zu wissen, was man tun sollte.
Ich dachte mir z.B., dass es sinnvoll ist, in der Ankernavi eine Kurzbeschreibung der objparams zu haben statt der Namen, da man ja normalerweise etwas Bestimmtes erreichen will und dann den Namen dazu sucht.

Kannst Du einfach auflisten, was Du anders machen würdest? Dann können wir das ja gern umsetzen oder ggf. diskutieren.

**Comment by AWqxKAWERbXo** [comment]
Für solche Fälle suche ich dann via GitHub.

**Comment by AWqxKAWERbXo** [comment]
Da sind leider bisher keine besseren Ideen vorhanden 
Und für die obj_params wäre die Umsetzung hier doch viel sinnvoller: https://github.com/yakamara/redaxo_yform/issues/95

**Comment by tbaddade** [comment]
> Und für die obj_params wäre die Umsetzung hier doch viel sinnvoller: yakamara/redaxo_yform#95

Das hat nichts mit dem Issue zu tun. 

Und da bisher keine anderen Ideen vorhanden sind, könnte das Issue dazu offen bleiben bis wir etwas gefunden haben.

**Comment by AWqxKAWERbXo** [comment]
Gibt es inzwischen neue Ideen hierzu?

**Comment by skerbis** [comment]
https://github.com/yakamara/redaxo_yform_docs/issues/161
