### ISSUE TITLE
Spamschutz via Zeitstempel

### ISSUE THREAD

**Issue by javanita** [yakamara/redaxo_yform_docs#68]
Da hat sich doch ein Tippfehler eingeschlichen. Im Funktionsnamen steht xform statt yform.

**Comment by AWqxKAWERbXo** [comment]
Gut aufgepasst, das Beispiel habe ich in R4 umgesetzt, aber für die R5-Doku geschrieben.

Danke für den Hinweis!

ist korrigiert...
