### ISSUE TITLE
Anleitung "Spamschutz" -> Google ReCaptcha

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#69]
Hat jemand schon mal diese Lösung verbaut?

**Comment by AWqxKAWERbXo** [comment]
In YForm 3.0 gibt es ein Recaptcha-Value, danke an @elpschulzo

Benötigt wird dazu ein ReCaptcha-v2-Schlüssel.

Pipe:
```
recaptcha|botcheck|PUBLIC_KEY_HIER|true
...
validate|recaptcha|botcheck|PRIVATE_KEY_HIER|Bitte führen Sie den Sicherheits-Check aus.
```

PHP:
```
$yform->setValueField('recaptcha', array('botcheck','PUBLIC_KEY','true'));
...
$yform->setValidateField('recaptcha', array("botcheck", "PRIVATE_KEY", "Bitte führen Sie den Sicherheits-Check aus."));
```

Keys können hier erstellt/abgerufen werden:
https://www.google.com/recaptcha/admin#list


Diese Infos müssen noch in die Doku übernommen werden.

**Comment by bitshiftersgmbh** [comment]
Ich übernehm die Doku. Danke @alexplusde für die gute Vorarbeit. <3

**Comment by AWqxKAWERbXo** [comment]
Statt Sicherheitscheck würde ich btw. wählen:
`Bitte bestätigen Sie, dass Ihre Nachricht kein Spam ist, indem Sie das Recaptcha-Feld ausfüllen.` o.ä.

**Comment by AWqxKAWERbXo** [comment]
@olien magst du hier evtl. die Doku vervollständigen, du warst doch letzt erst dabei, recaptcha einzurichten.

**Comment by olien** [comment]
Ich habs leider doch nicht umsetzen können. War eine individuelle Lösung und wir haben das zeitlich verschoben. Sollte ich es noch machen dokumentiere ich es selbstverständlich hier!
