### ISSUE TITLE
REX_YFORM_TABLE_DATA für Module

### ISSUE THREAD

**Issue by skerbis** [yakamara/redaxo_yform_docs#71]
Mit `REX_YFORM_TABLE_DATA` kann ein Auswahlwidget für yform-Tabellendaten ausgegeben werden. 

Multiple-Select - List
` REX_YFORM_TABLE_DATA[id="2" table="rex_downloads" widget="1" multiple="1" field="name,' ',info"]`

Single-Select-Widget
` REX_YFORM_TABLE_DATA[id="2" table="rex_downloads" widget="1" field="name,' ',info"]`

field= steuert hierbei die Listendarstellung. 
Die Ausgabe erfolgt als ID-Liste zur weiteren Verarbeitung

Ausgabe per: 
`REX_YFORM_TABLE_DATA[id=1]`

**Comment by AWqxKAWERbXo** [comment]
Kannst du hier einen Screenshot davon posten? Ich kann mir nichts darunter vorstellen.

**Comment by skerbis** [comment]
<img width="1277" alt="x2" src="https://user-images.githubusercontent.com/791247/74786975-501bae80-52ae-11ea-909b-e09f0eb234c9.png">

@alexplusde Code ist jetzt auf dem aktuellen Stand

**Comment by AWqxKAWERbXo** [comment]
Was? Das gibt's? Sowas habe ich schon 100x gebraucht und mir immer mit mform und selects gebastelt. Ist in YForm direkt mit drin?

Was heißt "Code ist auf dem aktuellen Stand"?

**Comment by tbaddade** [comment]
Hinweis hierzu: Man kann auch im [Redactor](https://github.com/FriendsOfREDAXO/redactor) ein Plugin aktivieren und so Text mit Yform-Datensätze verknüpfen.

**Comment by skerbis** [comment]
> Was? Das gibt's? Sowas habe ich schon 100x gebraucht

Äh, es stand hier seit 25.07.2017

> Was heißt "Code ist auf dem aktuellen Stand"?

@alexplusde  Die vorherige Schreibweise war von 2017 und wurde im Verlauf der Versionen noch verändert. Ich habe den Post aktualisiert, so dass es jetzt stimmt.

**Comment by darwin26** [comment]
REX_YFORM_TABLE_DATA - hätte nen Wunsch ... evtl erweitern um Filter, das z.B. die yForm tabelle nach aktueller clang gefilter werden kann ...

BSP:
REX_YFORM_TABLE_DATA[id="1" table="rex_meine_tabelle" widget="1" multiple="1" field="firstnamen, lastname,' filter="WHERE clang=1"]

kann auch alles mögliche dann filtern "WHERE color=red" .. etc...

oder gibts da bereits was?

@alexplusde -> kannst Du mir mal dein per Hand "gebasteltest" zeigen. Danke

**Comment by AWqxKAWERbXo** [comment]
@darwin26 nimm bei mForm ein select-Feld und gib dem ein Array, das du über sql anrufst.
