### ISSUE TITLE
Anleitung Spamschutz: via hidden E-Mail-Field

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_yform_docs#72]
Ich habe das wie unten angegeben benutzt. Kann das mal jemand prüfen bitte.

```
text|xmail|Ihre E-Mail-Adresse
text|email|Ihre E-Mail-Adresse

validate|empty|xmail|Bitte geben Sie Ihre E-Mail Adresse an
validate|email|xmail|Bitte geben Sie eine richtige E-Mail Adresse an
validate|compare_value|email|||Das Formular konnte nicht gesendet werden. Bitte kontaktieren Sie uns telefonisch
```

**Comment by AWqxKAWERbXo** [comment]
Verstehe nicht genau, was das Problem ist? Das E-Mail-Feld muss per CSS auf hidden gestellt werden.

**Comment by AWqxKAWERbXo** [comment]
> Kann sein, dass da das 2. Feld fehlt?

`validate|compare_value|email|xmail||Das Formular konnte nicht gesendet werden. Bitte kontaktieren Sie uns telefonisch`

oder so...?

**Comment by olien** [comment]
Ähm. Wenn ich so drauf gucke glaube ich, dass es so funktioniert wenn das E-Mail Feld hidden ist.
Ist leider schon zu lange her. Wollte es vermutlich nur nichts ungeprüft in die Docs schreiben zu dem Zeitpunkt :-)
