### ISSUE TITLE
Daterangepicker auf 2 inputs verteilen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform_docs#73]
Beispiel - Datum von / bis auf 2 Datenbankfelder verteilen.

Wie geht das mit dem jetzigen Picker? Ein kleines How-To wäre gut.

**Comment by AWqxKAWERbXo** [comment]
ich glaube, in dem Issue-Text ist Code verloren gegangen. Was meinst du?

**Comment by tbaddade** [comment]
Es gibt 2 input Felder: date_from und date_to. Klicke ich das from Feld öffnet sich der Picker und man wählt er einen Zeitraum von/bis. Jetzt wäre es gut, wenn der letzte Tag gleich in das to Feld landet.

**Comment by AWqxKAWERbXo** [comment]
Weiß ich leider auch nicht. Was spricht dagegen, eben jene Felder als zwei getrennte Auswahl-Felder festzulegen?

**Comment by tbaddade** [comment]
> Was spricht dagegen, eben jene Felder als zwei getrennte Auswahl-Felder festzulegen?

Die schnelle Möglichkeit einen Zeitraum auszuwählen. Außerdem ist es auch für die Augen und den Redakteur hilfreicher.

![screenshot 2017-10-05 08 46 27](https://user-images.githubusercontent.com/338267/31214059-c46b0aca-a9a9-11e7-88e0-8877be1ed489.png)

**Comment by AWqxKAWERbXo** [comment]
imho ist das ein Textfeld mit custom javascript dran. Man könnte ein Tutorial machen, wie man eigene Values, Actions und Validates erstellt und ggf. eigenes JS injiziert: #140 

Für mich kein extra Fall für die Doku, außer, du möchtest was schreiben.

**Comment by tbaddade** [comment]
Ein Textfeld ist es nicht ... es sollten zwei Felder vom Date Type sein, damit man die SQL Funktionen beim Query nutzen kann. Aber ich habe für mich eine Lösung gefunden.
