### ISSUE TITLE
Table Manager: manuelles Gruppieren von Feldern in Tabs u.ä.

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#76]
Siehe https://github.com/yakamara/redaxo_yform/issues/178

und Spalten-Layouts bei der Gelegenheit auch erwähnen.

@pixeldaniel vielleicht können wir da mal was zusammen schreiben?

**Comment by dergel** [comment]
weil im anderen issue im prinzip ok.. schliesse ich das hier .. best practise tricks gerne in die doku

**Comment by AWqxKAWERbXo** [comment]
Das ist das Doku-Repo, würde ich daher gerne offen lassen

**Comment by AWqxKAWERbXo** [comment]
https://github.com/FriendsOfREDAXO/tricks/issues/249
