### ISSUE TITLE
Modul: objparams ergänzen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#77]
es fehlen:
```
debug=[0/1]
hide_top_warning_messages=[0/1]
hide_field_warning_messages=[0/1]

getdata=[0/1]
main_where=[id=12]
main_id=[meineid]
main_table=[meinetabelle]
```
ursprüngliches Issue:
https://github.com/yakamara/redaxo_yform/issues/95

**Comment by AWqxKAWERbXo** [comment]
send = 1

**Comment by Goldfischpeter** [comment]
hide_field_warning_messages, soll das die Klasse has-error bei einem Feld unterdrücken?

$this->objparams['value_pool']['email']['ID'] = $this->objparams['main_id'];
Setzt das die ID in einem oder für ein E-Mail-Template?

**Comment by AWqxKAWERbXo** [comment]
> $this->objparams['value_pool']['email']['ID'] = $this->objparams['main_id'];

Ich glaube, damit bekommt man die id des gerade angelegten Datensatzes, habe es aber nicht ausprobiert...

**Comment by AWqxKAWERbXo** [comment]
Ist bereits genannt https://github.com/yakamara/redaxo_yform/blob/master/docs/formbuilder.md#objparams
