### ISSUE TITLE
Beispiel für Value-Klasse "hidden" ergänzen

### ISSUE THREAD

**Issue by greatif** [yakamara/redaxo_yform_docs#78]
@alexplusde 

In der Doku gibt es zum Value-Feld **hidden** zwar ein Beispiel zur Verwendung mit REQUEST in PIPE-Notation, jedoch keines in PHP-Schreibweise. Ein solches Beispiel wäre zu ergänzen.
Zudem könnte eine kurze Erklärung zu REQUEST hilfreich sein.

**Comment by AWqxKAWERbXo** [comment]
https://redaxo.org/forum/viewtopic.php?t=19882&p=111158
https://redaxo.org/forum/addons-r4-f30/xform-daten-weiterverarbeitung-t17891.html#p98118
https://redaxo.org/forum/addons-r4-f30/xform-daten-weiterverarbeitung-t17891.html#p98260

Unserer Unterhaltung auf Slack voraus: 

Mit `hidden|test|$var||no_db` oder `$yform->setValueField('hidden', array('test', $var, ''))` hätte es bei dir funktionieren müssen, vlt. kannst du das nochmal kurz testen. Den REQUEST-Parameter musst du ja nicht setzen, weil du den Default-Parameter direkt befüllst und nicht aus der URL oder via POST holst.

**Comment by greatif** [comment]
Nur der Klarheit halber, ich denke, Du meinst wohl:
`$yform->setValueField('hidden', array('test', $var, ''));`.

Aber nein, das funktioniert nicht *(weder mit noch ohne Request-Parameter)*.
Es wird in beiden Fällen durch `REX_YFORM_DATA[field="test"]` dann in einer E-Mail nur "**test**" ausgegeben, nicht der Inhalt von `$var`.

Verwende ich hingegen:
`$yform->setValueField('text', array('test',"$var'','{"type":"hidden"}'));`
wird via *REX_YFORM_DATA[field="test"]* der Inhalt von *$var* ausgegeben.

**Comment by AWqxKAWERbXo** [comment]
Ok, dann dürfte das ein Bug sein und ich kläre das mal ab, bevor ich es in die Doku übernehme.

Klar, bei der 2. Variante hast du im Quellcode dann auch ein ausgeblendetes Input-Feld. Wenn das für dich so passt, ist das kein Problem (theoretisch könnte jemand den Wert vor dem Absenden manipulieren)

**Comment by AWqxKAWERbXo** [comment]
Syntax-Fehler, es muss wohl lauten:

`$yform->setValueField('hidden', array('test', '', $var)`
