### ISSUE TITLE
Formbuilder: objparams genauer erklären

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#8]
https://github.com/yakamara/redaxo_yform/issues/95

@tbaddade

**Comment by polarpixel** [comment]
Die sind doch schon vollständig dokumentiert, oder nicht?
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yform_modul_objparams.md

**Comment by AWqxKAWERbXo** [comment]
Mittlerweile... das Issue war sicher erstellt, als das noch nicht der Fall war.

**Comment by polarpixel** [comment]
Ok, hatte ich eben erst bemerkt.

**Comment by tbaddade** [comment]
Mir würde diese Übersicht mit den Default-Values noch fehlen. https://github.com/yakamara/redaxo_yform/blob/master/lib/yform.php#L20-L94

**Comment by AWqxKAWERbXo** [comment]
~@Goldfischpeter war deine Baustelle, oder?~

**Comment by polarpixel** [comment]
Ne, meine.

@tbaddade Zum Teil sind diese Values erklärt.
Ich würde dann die noch fehlenden ergänzen.
Oder findest Du, dass diese Values zusätzlich als die in der yform-Hauptdatei vordefinierten noch aufgelistet werden sollten?

**Comment by tbaddade** [comment]
Ich finde die Liste so wie sie ist recht übersichtlich. Eventuell zusätzlich mit in die TOC aufnehmen und dann einfach zur Beschreibung verlinken?

**Comment by polarpixel** [comment]
Also:
- die fehlenden Values ergänzen
- und dann den oben von Dir geposteten Link mit aufnehmen

Habe ich Dich so richtig verstanden?

**Comment by tbaddade** [comment]
Ich meinte in etwa so:
- List aller Objparams
  - [objparams['submit_btn_label']](#submit-benennen)
  - [objparams['submit_btn_show']](#submit-anzeigen)

Oder den Link, wobei der Link durch die Zeilenangabe variieren kann.

**Comment by AWqxKAWERbXo** [comment]
@polarpixel meinst du, du würdest hier noch was ergänzen?

**Comment by AWqxKAWERbXo** [comment]
@polarpixel ?
