### ISSUE TITLE
Tools-Plugin : Hinweis anzeigen, wenn das PlugIn nicht installiert ist

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform_docs#81]

**Comment by AWqxKAWERbXo** [comment]
Du meinst das Addon yform_usability? Warum sollte das Aufgabe der Doku sein?

**Comment by tbaddade** [comment]
Nein, ich meine das Tools PlugIn von YForm.

**Comment by AWqxKAWERbXo** [comment]
Sehe trotzdem nicht, warum die Doku das leisten können muss, vielleicht gibt es noch andere Meinungen?
