### ISSUE TITLE
Doku: Erstellung hidden-Feld

### ISSUE THREAD

**Issue by shauste** [yakamara/redaxo_yform_docs#82]
Betrifft das Anlegen eines hidden-Feld.
In der Doku ist ein **Hinweis vermerkt, der verwirrt:**
_Hinweis: Für ein unsichtbares Eingabefeld wird nicht dieses hidden-Feld verwendet, sondern bspw. ein reguläres Eingabefeld (text), das zusätzlich das Attribut type="hidden" bekommt._
(Quelle: https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yform_modul_values.md#hidden)

Besser ist **stattdessen** folgende Funktion zu verwenden: $yform->setHiddenField(‘name’, “value”);

**Comment by AWqxKAWERbXo** [comment]
Es kommt darauf an, ob man ein Value clientseitig oder serverseitig befüllen will.

In der Regel will man das Feld serverseitig befüllen und dem Client nicht die Möglichkeit bieten, es zu manipulieren.

Es wurde allerdings auch immer wieder gefragt, wie man ein klassisches `<input type="hidden" />`-Feld anlegt, daher die Erläuterung. Wie würdest du es formulieren? @shauste 

Vielleicht wäre es besser, die Methode einfach setValue() zu nennen?

**Comment by AWqxKAWERbXo** [comment]
Das Beispiel  in diesem Issue oben ist verkehrt. Richtig ist:
https://github.com/yakamara/redaxo_yform_docs/issues/78#issuecomment-489164090
