### ISSUE TITLE
Datensatz bearbeiten

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#86]
via @IngoWinter 

```
$f = new rex_yform();
$f->setDebug();
$f->setObjectparams('main_table', 'rex_deine_tabelle');
$f->setObjectparams('main_where', 'id=' . $deine_id);
$f->setObjectparams('form_action', rex_getUrl('REX_ARTICLE_ID'));

// hier dein formular

$f->setFormData('action|db|rex_deine_tabelle|main_where');

echo $f->getForm();
```

PR gerne angenommen.

**Comment by AWqxKAWERbXo** [comment]
@IngoWinter würdest du das immer noch so machen? warum setFormData und dann eine Pipe-Notation? Wie müsste das ganze im Formbuilder-Modul aussehen?

**Comment by IngoWinter** [comment]
Ich habe keine Ahnung wann ich das in welchem Kontext geschrieben habe. Mittlerweile bin ich komplett von der Pipe Geschichte ab, deswegen würde ich es nicht mehr so machen.

**Comment by AWqxKAWERbXo** [comment]
Wie wäre die Umsetzung aktuell?

**Comment by IngoWinter** [comment]
vermutlich setActionField('db... irgendwas :)

**Comment by AWqxKAWERbXo** [comment]
Ach Gott, jetzt verstehe ich es...

**Comment by schorschy** [comment]
close @alexplusde ?

**Comment by AWqxKAWERbXo** [comment]
@schorschy hast du es in die Doku übernommen?

**Comment by schorschy** [comment]
nein, klang nur so als hätte sich das hier erledigt. ich wollte einfach mal bei dem ein oder anderen alten issue nachhaken wie es aussieht um aufzuräumen.

**Comment by AWqxKAWERbXo** [comment]
Dann lieber gleich einen PR machen. Was offen ist, ist mit sehr hoher Wahrscheinlichkeit offen.

**Comment by skerbis** [comment]
@alexplusde https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yform_modul_actions.md#db
Steht doch hier. Close?

**Comment by AWqxKAWERbXo** [comment]
Bitte offen lassen, ich sehe hier folgende Probleme

* Unverständlich: Es werden in einem Pipe-Block 2 Beispiele erklärt -> Beispiele verbessern
* Schwer zu finden: Wer einen "Datensatz bearbeiten" möchte, weiß noch nicht, dass er in der db-Action fündig wird. -> Ich wäre für ein eigenes kleines Howto ("Datensätze im Frontend bearbeiten")
* Inkonsistent: PHP und Pipe-Beispiele unterscheiden sich voneinander
