### ISSUE TITLE
CSRF-Schutz erwähnen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_yform_docs#89]

**Comment by AWqxKAWERbXo** [comment]
@dergel mir fällt es immer noch schwer, den zu erklären und zu erläutern, wann er abgeschalten werden darf und wann es eigentlich keine gute Idee ist, ihn zu deaktivieren.

In etwa so:

> Der Parameter zum CSRF-Schutz (Cross-Site-Request-Forgery, auch XSRF) verhindert, dass speziell präparierte Anfragen von YForm ausgeführt werden. Angriffsszenario auf ein YForm-Formular wäre bspw. ein Nutzer, der einen präparierten Link erhält und durch einen Klick dann Daten seines REDAXO-Besuchs preisgibt oder unbemerkte/ungewollte Aktionen durch das YForm-Formular ausführt. 
>
> Vereinfacht gesagt sorgt der CSRF-Schutz dafür, dass Formulare nur dann erfolgreich abgesendet werden, wenn der Nutzer sich zum Zeitpunkt des Formular-Absendens auf der Seite befunden hat.
>
>Der CSRF-Schutz sollte daher immer aktiviert bleiben, außer, wenn der direkte Aufruf und Versand eines Formulars explizit durch einen präparierten Link erfolgen muss - bspw. beim Account-Aktivieren-Link des Addons YCom.

**Comment by dergel** [comment]
ist doch gut beschrieben.. es gibt so gut wie keinen Grund zu deaktivieren.. ausser dem, den du genannt hast
