### ISSUE TITLE
Artikel zusammenführen?

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform_docs#92]
Ist es beabsichtigt dies auf 2 Seiten aufzuteilen bzw. spricht was dagegen diese 2 Artikel zusammenzufassen?

https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/table_manager_feldtypen.md
https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/yform_modul_values.md

**Comment by AWqxKAWERbXo** [comment]
Wurde von zwei unterschiedlichen Autoren verfasst und unterscheidet sich im Detail. War auch unglücklich damit, weiß aber nicht mehr, warum ich es gar nicht erst zur Sprache gebracht habe.

**Comment by AWqxKAWERbXo** [comment]
Ach ja, die be_manager-Felder gibts bspw nur im Table Manager, auch die Eingabefelder im Backend.

**Comment by AWqxKAWERbXo** [comment]
Sehe es auch Monate später als beabsichtigt an, auch wenn sich Dopplungen dadurch ergeben. Wäre eher dafür, die beiden Seiten qualitativ und im Schreibstil anzugleichen.

**Comment by tbaddade** [comment]
Ich bin durch diese zwei Artikel sehr oft am suchen und verwende zumeist erst immer den falschen Artikel. Finde das nach wie vor grad nicht optimal. Aber besser so als gar nichts. :)
