### ISSUE TITLE
Action `manage_db` fehlt

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform_docs#94]

**Comment by AWqxKAWERbXo** [comment]
https://github.com/yakamara/redaxo_yform/blob/master/plugins/manager/lib/yform/action/manage_db.php

Im Code wurde keine Beschreibung der Parameter hinterlegt. Deswegen taucht diese Action auch nicht öffentlich auf. Was kann sie denn?

**Comment by AWqxKAWERbXo** [comment]
@tbaddade @dergel für was ist die Action da?

**Comment by AWqxKAWERbXo** [comment]
Ping

**Comment by tbaddade** [comment]
Die Action legt nicht vorhandene Felder an.

**Comment by AWqxKAWERbXo** [comment]
Ist das die action, die früher `create_db` hieß?

**Comment by tbaddade** [comment]
> Ist das die action, die früher create_db hieß?

Nein, da es die Action `createdb` auch noch gibt. Genaueres müsste @dergel erklären.
