### ISSUE TITLE
Translation from yform_docs to Spanish

### ISSUE THREAD

**Issue by nandes2062** [yakamara/redaxo_yform_docs#95]
Is there a possibility to translate into Spanish? If so, how do I start?

**Comment by AWqxKAWERbXo** [comment]
Hey @nandes2062, you could 
* just fork the repo or 
* download the `de_de` folder and rename it to `es_es`

**Comment by AWqxKAWERbXo** [comment]
@nandes2062 have you been able to start with the translation?

**Comment by AWqxKAWERbXo** [comment]
@gharlan @dergel 

Is it possible to give @nandes2062 access to YTraduco? 

Nandes, are you still interested in translating?

**Comment by gharlan** [comment]
He already has access to ytraduko.
All these pull requests are changes made by @nandes2062:
https://github.com/pulls?page=1&q=is%3Apr+author%3Aytraduko-bot+archived%3Afalse+is%3Aclosed+nandes2062&utf8=✓

**Comment by AWqxKAWERbXo** [comment]
thx
