### ISSUE TITLE
be_manager_relation - Korrekturen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_yform_docs#97]
Es geht um diese [Datei](https://github.com/yakamara/redaxo_yform_docs/blob/master/de_de/table_manager_feldtypen_be-manager-relation.md
)

1. Das Feld heißt `be_manager_relation`. Es wird jedoch sehr oft von [be_relation](url) geschrieben
1. Many to Many (m:n) > Schritt 2 - Hilfstabelle verknüpfen > Mehrfachauswahl
Das können auch die `single` Optionen sein und die `Leeroption` kann auch angehakelt werden
Das ist dann sinnvoll, wenn man in beiden Tabellen die Datensätze gegenseitig verknüpfen möchte.

**Comment by AWqxKAWERbXo** [comment]
1. habe ich korrigiert.
2. verstehe ich nicht.

**Comment by tbaddade** [comment]
zu 1.
Super danke dir

zu 2.

Aktuell steht
`select (multiple) oder popup (multilple)`… Hier fehlt die Info das es auch `single` sein kann

Und die `Leeroption` sollte man, wegen diesen Text `nicht erwähnte Optionen bleiben unverändert` nicht anhaken.

**Comment by AWqxKAWERbXo** [comment]
Ok, ich habe es wage verstanden, muss es mir mal genauer anschauen. YForm macht inzwischen @Pixeldaniel so gut bei uns, dass ich ziemlich raus bin...

**Comment by AWqxKAWERbXo** [comment]
@tbaddade schau mal, ob's so passt. Ich nehme es mal an.
